APIS-6541: more domain classes in the library
hmrc/api-platform-application-domain pull request #23
Opened 2023-11-13 15:35 UTC by mattclark-zerogravit

2023-11-13 15:52 UTC, peteslater-ee commented on src/main/scala/uk/gov/hmrc/apiplatform/modules/applications/core/interface/models/UpliftRequest.scala
> +  )
Formatting here seems wrong

2023-11-13 15:53 UTC, peteslater-ee requested changes
I left a couple of comments

2023-11-14 07:01 UTC, mattclark-zerogravit commented on src/main/scala/uk/gov/hmrc/apiplatform/modules/applications/core/interface/models/CreateApplicationRequest.scala
> +    println(in.collaborators.map(_.normalise))
good spot, will remove.

2023-11-14 07:16 UTC, peteslater-ee approved these changes

2023-11-14 07:16 UTC, merged