API 7560: allow grant-length to be a Period
hmrc/api-platform-application-domain pull request #45
Opened 2024-03-14 16:51 UTC by worthydolt

2024-03-20 10:19 UTC, johnsgp commented on src/main/scala/uk/gov/hmrc/apiplatform/modules/applications/core/domain/models/GrantLength.scala
> +  val unitRead: Reads[String] = (JsPath \ "unit").read[String].map(u => u.toUpperCase)
Could these be private?

2024-03-20 10:19 UTC, johnsgp commented on src/main/scala/uk/gov/hmrc/apiplatform/modules/applications/core/domain/models/GrantLength.scala
> +    (JsPath \ "length").write[Long] and
The `java.time.Duration.of(long amount, TemporalUnit unit)` method calls this `amount` (see [Javadoc](https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/time/Duration.html#of(long,java.time.temporal.TemporalUnit))). Should we keep it the same? The word `length` has a different scientific meaning.

2024-03-20 10:37 UTC, anjumabbas5 commented on src/test/scala/uk/gov/hmrc/apiplatform/modules/applications/core/domain/models/GrantLengthSpec.scala
> +
We already have one "read from json where grant length is Duration"

2024-03-20 12:17 UTC, johnsgp commented on src/test/scala/uk/gov/hmrc/apiplatform/modules/applications/core/domain/models/GrantLengthSpec.scala
> +
That one is not testing GrantLength using the Duration though. I was thinking of a test with:
```GrantLength.apply(1, "DAYS")```

2024-03-20 14:55 UTC, anjumabbas5 commented on src/test/scala/uk/gov/hmrc/apiplatform/modules/applications/core/domain/models/GrantLengthSpec.scala
> +
In the test I mentioned above the grant length reader will call the 2-parameter `.apply`. Hence it showing as covered in the coverage report.

2024-03-20 15:07 UTC, anjumabbas5 commented on src/test/scala/uk/gov/hmrc/apiplatform/modules/applications/core/domain/models/GrantLengthSpec.scala
> +
@johnsgp saying that I've added a test to GrantLengthSpec

2024-03-22 07:56 UTC, johnsgp commented on src/main/scala/uk/gov/hmrc/apiplatform/modules/applications/core/domain/models/GrantLength.scala
> +  )(d => (d.toSeconds, ChronoUnit.SECONDS.name()))
If you publish this library locally and test it with, say, third-party-application, what happens with the repository reads and writes? Is there a clash? Do they uses these formatters or db-specific ones?

2024-03-27 07:47 UTC, AndySpaven requested changes

2024-03-27 07:47 UTC, AndySpaven commented on src/test/scala/uk/gov/hmrc/apiplatform/modules/applications/core/domain/models/GrantLengthSpec.scala
> +      val e = intercept[IllegalStateException] {
This should not have thrown but instead returned a JsError

2024-03-27 07:47 UTC, AndySpaven commented on src/main/scala/uk/gov/hmrc/apiplatform/modules/applications/core/domain/models/GrantLength.scala
> +    JsPath.read[Period].flatMapResult {
This needs to not throw an exception - perhaps change this apply to also return option then pattern match or fold on the option of grantlength to return (js)success or (js)error

2024-03-27 07:47 UTC, AndySpaven commented on src/main/scala/uk/gov/hmrc/apiplatform/modules/applications/core/domain/models/GrantLength.scala
> +  def apply(period: Period): GrantLength = {
Probably need to change to  option of grantlength (see comments below)

2024-03-27 14:23 UTC, AndySpaven approved these changes

2024-03-27 15:43 UTC, merged