APIS-7046: Added new commands and tests
hmrc/api-platform-application-domain pull request #47
Opened 2024-05-01 14:52 UTC by mattclark-zerogravit

2024-05-02 14:08 UTC, petekirby-ee requested changes

2024-05-02 14:08 UTC, petekirby-ee commented on src/main/scala/uk/gov/hmrc/apiplatform/modules/commands/applications/domain/models/ApplicationCommand.scala
> +  case class GrantApplicationApprovalRequestWithWarnings(gatekeeperUser: String, timestamp: Instant, warnings: String, escalatedTo: String)              extends SubmissionCommand
I think that escalatedTo should be optional

2024-05-02 14:08 UTC, petekirby-ee commented on src/main/scala/uk/gov/hmrc/apiplatform/modules/commands/applications/domain/models/ApplicationCommand.scala
> +  case class GrantTermsOfUseApproval(gatekeeperUser: String, timestamp: Instant, reasons: String, escalatedTo: String)                                   extends SubmissionCommand with GatekeeperMixin
I think that escalatedTo should be optional

2024-05-03 07:02 UTC, mattclark-zerogravit commented on src/main/scala/uk/gov/hmrc/apiplatform/modules/commands/applications/domain/models/ApplicationCommand.scala
> +  case class GrantApplicationApprovalRequestWithWarnings(gatekeeperUser: String, timestamp: Instant, warnings: String, escalatedTo: String)              extends SubmissionCommand
ok will sort

2024-05-03 07:51 UTC, mattclark-zerogravit commented on src/main/scala/uk/gov/hmrc/apiplatform/modules/commands/applications/domain/models/ApplicationCommand.scala
> +  case class GrantTermsOfUseApproval(gatekeeperUser: String, timestamp: Instant, reasons: String, escalatedTo: String)                                   extends SubmissionCommand with GatekeeperMixin
OK will sort

2024-05-03 07:54 UTC, petekirby-ee approved these changes

2024-05-03 08:17 UTC, merged